name: Build JOSS Paper PDF

on:
  push:
    paths:
      - paper/**
      - .github/workflows/build-joss-paper.yml

jobs:
  build-paper:
    runs-on: ubuntu-latest
    name: Generate JOSS Paper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile JOSS PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper
          path: paper/paper.pdf
